StockExchangeHelper/Models/ExchangeRate.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StockExchangeHelper.Models
{
    public class ExchangeRate
    {
        public int Id { get; set; }
        public string Currency { get; set; }

        [Required]
        [RegularExpression(@"[a-zA-Z]{3}", ErrorMessage = "Required 3 letter code of currency.")]
        public string Code { get; set; }

        public double AverageRate { get; set; }
        public double StandardDeviation { get; set; }

        [Required]
        [DateLessThan("EndDate")]
        [Display(Name = "Start Date Time")]
        public DateTime StartDate { get; set; } = DateTime.Today - TimeSpan.FromDays(7);

        [Required]
        [Display(Name = "End Date Time")]
        public DateTime EndDate { get; set; } = DateTime.Today;

        public DateTime SaveDate { get; set; }

        public override string ToString()
        {
            return
                $"{Currency} - {Code}, Average : {AverageRate}, StandardDeviation : {StandardDeviation}, from : {StartDate.ToShortDateString()} to : {EndDate.ToShortDateString()}, Saved at : {SaveDate}";
        }
    }
}

StockExchangeHelper/ViewModels/ExchangeRateViewModel.cs
using StockExchangeHelper.Models;

namespace StockExchangeHelper.ViewModels
{
    public class ExchangeRateViewModel
    {
        public ExchangeRate ExchangeRate { get; set; }
        public string ExceptionMessage { get; set; }
    }
}

StockExchangeHelper/Controllers/ExchangeRateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using NLog;
using StockExchangeHelper.ExtensionMethods;
using StockExchangeHelper.Interfaces;
using StockExchangeHelper.Models;
using StockExchangeHelper.ViewModels;

namespace StockExchangeHelper.Controllers
{
    public class ExchangeRateController : Controller
    {
        private static Logger _logger;
        private readonly ApplicationDbContext _context;
        private readonly ICurrencyExchangeService _currencyExchangeService;

        public ExchangeRateController(ICurrencyExchangeService currencyExchangeService)
        {
            _currencyExchangeService = currencyExchangeService;
            _context = new ApplicationDbContext();
            _logger = LogManager.GetCurrentClassLogger();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult GetHistoryResults()
        {
            var rates = new List<ExchangeRate>();
            if (_context.ExchangeRates != null)
            {
                 rates = _context.ExchangeRates.ToList();
            }
            
            return View(rates);
        }

        public ActionResult GetRate()
        {
            var exchangeRateViewModel = new ExchangeRateViewModel
            {
                ExchangeRate = new ExchangeRate()
            };
            return View("ExchangeRateForm", exchangeRateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendRequest(ExchangeRateViewModel viewModel)
        {
            viewModel.ExceptionMessage = null;
            if (!ModelState.IsValid)
            {
                _logger.Warn("Trial of sending incorrect request.");
                return View("ExchangeRateForm", viewModel);
            }

            try
            {
                viewModel.ExchangeRate = _currencyExchangeService.GetExchangeRate(
                    viewModel.ExchangeRate.StartDate,
                    viewModel.ExchangeRate.EndDate,
                    viewModel.ExchangeRate.Code);

                viewModel.ExchangeRate.SaveDate = DateTime.Now;
                ReportRecord(viewModel.ExchangeRate);
            }
            catch (Exception e)
            {
                _logger.Error(e.Message);
                viewModel.ExceptionMessage = e.Message;
                return View("ExchangeRateForm", viewModel);
            }

            return View("Result", viewModel.ExchangeRate);
        }

        private void ReportRecord(ExchangeRate exchangeRate)
        {
            const string reportsPath = @"C:\temp\";
            if (!Directory.Exists(reportsPath))
                Directory.CreateDirectory(reportsPath);

            exchangeRate.SaveToXmlReport(reportsPath);
            _context.ExchangeRates.Add(exchangeRate);
            _context.SaveChanges();
            _logger.Info($"Record was correctly saved. {exchangeRate}");
        }
    }
}

StockExchangeHelper/Controllers/api/ExchangeRatesController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Http;
using StockExchangeHelper.Interfaces;
using StockExchangeHelper.Models;

namespace StockExchangeHelper.Controllers.Api
{
    public class ExchangeRatesController : ApiController
    {
        private readonly ApplicationDbContext _context;
        private readonly ICurrencyExchangeService _currencyExchangeService;

        public ExchangeRatesController()
        {
            _context = new ApplicationDbContext();
            _currencyExchangeService = new NbpOverlay();
        }

        [HttpGet]
        public IHttpActionResult GetExchangeRates()
        {
            return Ok(_context.ExchangeRates.ToList());
        }

        [HttpGet]
        public IHttpActionResult GetExchangeRate(int id)
        {
            var exchangeRate = _context.ExchangeRates.SingleOrDefault(x => x.Id == id);
            if (exchangeRate == null)
                return NotFound();

            return Ok(exchangeRate);
        }

        [HttpPost]
        public IHttpActionResult SendExchangeRate(ExchangeRate exchangeRate)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            exchangeRate = _currencyExchangeService.GetExchangeRate(
                exchangeRate.StartDate,
                exchangeRate.EndDate,
                exchangeRate.Code);

            exchangeRate.SaveDate = DateTime.Now;

            _context.ExchangeRates.Add(exchangeRate);
            _context.SaveChanges();

            return Created(new Uri(Request.RequestUri + "/" + exchangeRate.Id), exchangeRate);
        }

        [HttpDelete]
        public void DeleteExchangeRate(int id)
        {
            var exchangeRateInDb = _context.ExchangeRates.SingleOrDefault(x => x.Id == id);
            if (exchangeRateInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.ExchangeRates.Remove(exchangeRateInDb);
            _context.SaveChanges();
        }
    }
}

StockExchangeHelper/Views/ExchangeRate/ExchangeRateForm.cshtml
@model StockExchangeHelper.ViewModels.ExchangeRateViewModel

@{
    ViewBag.Title = "ExchangeRateForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Get information about currency in specific time period.</h2>

<div id="Exchange Rate Form">
    @using (Html.BeginForm("SendRequest", "ExchangeRate"))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.ExchangeRate.StartDate)
            @Html.TextBoxFor(x => x.ExchangeRate.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ExchangeRate.StartDate)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.ExchangeRate.EndDate)
            @Html.TextBoxFor(x => x.ExchangeRate.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ExchangeRate.EndDate)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.ExchangeRate.Code)
            @Html.TextBoxFor(x => x.ExchangeRate.Code, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ExchangeRate.Code)
        </div>

        @Html.HiddenFor(x => x.ExchangeRate.Id)
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-primary">Get</button>

        if (Model.ExceptionMessage != null)
        {
            <h2>@Model.ExceptionMessage</h2>
        }
    }
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

StockExchangeHelper/Views/ExchangeRate/GetHistoryResults.cshtml
@model List<StockExchangeHelper.Models.ExchangeRate>

@{
    ViewBag.Title = "History Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>History of exchange rate searches</h2>

@if(@Model != null){
<table style="width:100%">
    <tr>
        <th>Id</th>
        <th>Currency</th>
        <th>Code</th>
        <th>Average Rate</th>
        <th>Standard Deviation</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Save Date</th>
    </tr>
    @foreach (var rate in @Model)
    {
    <tr>
        <td>@rate.Id</td>
        <td>@rate.Currency</td>
        <td>@rate.Code</td>
        <td>@rate.AverageRate</td>
        <td>@rate.StandardDeviation</td>
        <td>@rate.StartDate.ToShortDateString()</td>
        <td>@rate.EndDate.ToShortDateString()</td>
        <td>@rate.SaveDate</td>
    </tr>
    }
</table>
}else{
<h2>There is no records!</h2>}

StockExchangeHelper/Views/ExchangeRate/Result.cshtml
@model StockExchangeHelper.Models.ExchangeRate
@{
    ViewBag.Title = "Exchange Rate Api";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Currency - @Model.Code</h2>
<h4>
    @Model.StartDate.ToShortDateString() - @Model.EndDate.ToShortDateString() 
    <br/>
    Average rate : @Model.AverageRate.ToString("F4")  Standard Deviation : @Model.StandardDeviation.ToString("F4")
</h4>